import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle', timeout: 20000 });
await page.waitForTimeout(2500);
await page.evaluate(() => document.body.scrollTo({ top: 0, behavior: 'instant' }));
await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/app-hero.png' });
await browser.close();
console.log('Done');
